# simple knative application to display the routed messages
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudevent-display
spec:
  template:
    spec:
      containers:
        - env:
            - name: K_SINK
              value: >-
                http://broker-ingress.kogito-knative-bug.svc.cluster.local/kogito-knative-bug/default
          image: registry.hub.docker.com/mouachani/cloudevent-display