apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kogito-kafka-source
spec:
  consumerGroup: eligibility
  bootstrapServers:
    - kogito-kafka-infra-kafka-bootstrap:9092
  topics:
    - eligibilityapplication
  sink:
    ref: 
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eligibility